### ISSUE TITLE
dot file permission is incorrect.(---x-wx--T)

### ISSUE THREAD

**Issue by prprhyt** [grant/dotf#5]
npm test is failed.  

```
npm test

> dotf@1.1.0 test /Users/prprhyt/gitdir/dotf
> ava


  2 passed
  2 failed

  read

  Rejected promise returned by test. Reason:

  Error {
    code: 'EACCES',
    errno: -13,
    path: '/Users/prprhyt/.myrc3',
    syscall: 'open',
    message: 'EACCES: permission denied, open \'/Users/prprhyt/.myrc3\'',
  }



  write
  /Users/prprhyt/gitdir/dotf/test.js:19

   18:       parseInt(777, 8)).toString(8)) {
   19:     t.fail();                         
   20:   }                                   

  Test failed via `t.fail()`
npm ERR! Test failed.  See above for more details.
```

It looks like to set wrong permission in https://github.com/grant/dotf/commit/87d53f7aa237db5eeee14bfdc96116edf59b9f30#diff-168726dbe96b3ce427e7fedce31bb0bcR36.  
> fs.chmodSync(fullpath, 600);  

It seems to be incorrect.  
I think 0600 is correct.  
fs.chmodSync's 2nd args is derived from  C lang chmod function in sys/stat.h.  
> int chmod(const char *pathname, mode_t mode);

See:
- http://man7.org/linux/man-pages/man2/chmod.2.html  
- https://nodejs.org/api/fs.html#fs_fs_chmodsync_path_mode

**Comment by grant** [comment]
Yes, I think `600` was a mistake. See `1.1.1`.
Please make a PR if you think we could use the constants rather than the literal `0600`.
